### ISSUE TITLE
installation from a direct connection

### ISSUE THREAD

**Issue by jinz2014** [Xilinx/PYNQ-HelloWorld#11]
I have a question about the installation. The PYNQ board has a direct connection with a development machine, so the direct board-to-computer connection prevents the board from directly accessing the internet. How can I  install and run an example  ? 

Thank you for your instructions very much.

**Comment by cathalmccabe** [comment]
1. Download a zip of this project
2. Copy it to the board
3. Unzip
4. Run 'pip install' on the local directory
