### ISSUE TITLE
`xf_config_params.h` bound from the test instead of the actual example

### ISSUE THREAD

**Issue by goekce** [Xilinx/PYNQ-HelloWorld#23]
I see that `xf_config_params.h` is included from [a specific test](https://github.com/Xilinx/Vitis_Libraries/blob/40b98f7a20d4f9d181642104f74d797a94315024/vision/L2/tests/resize/resize_DOWN_BILINEAR_NO_RGB/xf_config_params.h) instead of the [actual source](https://github.com/Xilinx/Vitis_Libraries/blob/40b98f7a20d4f9d181642104f74d797a94315024/vision/L2/examples/resize/build/xf_config_params.h):

https://github.com/Xilinx/PYNQ-HelloWorld/blob/b9ec77a8d01f8b77acb9a1ca5047b3a0866c6e49/boards/ip/hls/resize/script.tcl#L10

These `xf_config_params.h` do not differ. Is there a logic behind including the file from the test?

**Comment by mariodruiz** [comment]
They do differ, in particular `#define RGB 1` and `#define INTERPOLATION 1`
