### ISSUE TITLE
KV260 Image

### ISSUE THREAD

**Issue by ombhilare999** [Xilinx/PYNQ-HelloWorld#28]
Hi, I see that KV260 is also supported for this example, which image are you using for this?
As of now, I don't see any official version for same. Can you guys share your custom image?
Thank you.

**Comment by schelleg** [comment]
Kria-PYNQ launched ... this was the image used for testing.
https://discuss.pynq.io/t/pynq-now-available-for-the-kria-kv260-vision-ai-starter-kit/3579/2
