### ISSUE TITLE
Replace DMA with AXI Master

### ISSUE THREAD

**Issue by haipnh** [Xilinx/PYNQ-HelloWorld#29]
Hi,

In this repo, we use DMA and the performance is poor. I guess it was because of the DMA & Data Width Converters. 
However, if we want to replace the DMA with AXI Master, how can we use the kernel on IPython?

I tried allocating the buffers in PS memory, then passed their physical address to the kernel and set AP_CTRL=1. It returned a black image.

I think this approach helps user to go straight from kernel development to application development with Vitis, bypass the complicated system block design with Vivado.

Old:
![Old](https://aws1.discourse-cdn.com/business5/uploads/pynq1/original/2X/6/641a9ce64a2d027a2843a95f66fd9c4bdc342291.png)

Suggest:
![Suggest](https://aws1.discourse-cdn.com/business5/uploads/pynq1/original/2X/c/ce79368621dea24aa2b534bb4345b33e42c3504f.png)

**Comment by mariodruiz** [comment]
This won't be supported in this repo. You can take inspiration from this thread https://discuss.pynq.io/t/tutorial-axi-master-interfaces-with-hls-ip/4032

**Comment by haipnh** [comment]
Thank you for the info., Mario.
